name: Deploy

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repo
              uses: actions/checkout@v4

            - name: Install pnpm
              uses: pnpm/action-setup@v4
              with:
                  version: latest

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Deploy
              env:
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  DATABASE_URL: ${{ secrets.DATABASE_URL }}
                  NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
                  CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}
                  XATA_API_KEY: ${{ secrets.XATA_API_KEY }}
                  XATA_BRANCH: ${{ secrets.XATA_BRANCH }}
              run: pnpm exec sst deploy --stage=production
